# Generated by Django 4.2.1 on 2023-09-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcode', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('campus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Passkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('passkey', models.CharField(max_length=4)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('place_of_birth_city', models.CharField(max_length=50)),
                ('birth_state', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('whatsapp_no', models.CharField(max_length=50)),
                ('college_state', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('passing_year', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('permanent_address', models.CharField(max_length=50)),
            ],
        ),
    ]
